Tracker:AddItems("items/bosses.json")
Tracker:AddItems("items/events.json")
Tracker:AddItems("items/items.json")
Tracker:AddItems("items/hosted_items.json")
Tracker:AddItems("items/settings.json")
